	select @SRC_MISS_Cnt = count(*)
	from [<TARGET_DATABASE>].[<TARGET_SCHEMA>].[<TARGET_TABLE>] trg with (nolock)
	where not exists (
	    select *
	    FROM <SOURCE_SERVER_SELECT>[<SOURCE_DATABASE>].[<SOURCE_SCHEMA>].[<SOURCE_TABLE>] src with(nolock)
	    where <SOURCE_TABLE_SEARCH_COLUMN> between @SPERIOD_START_DTTM and @SPERIOD_END_DTTM AND <TARGET_PK_CONDITION>
	)
	and <TARGET_TABLE_SEARCH_COLUMN> between @SPERIOD_START_DTTM and @SPERIOD_END_DTTM;

	SET @ERR1 = @@ERROR;

	select @TRG_MISS_Cnt = count(*), @MIN_MISS_DTTM = MIN(<SOURCE_TABLE_SEARCH_COLUMN>)
	from <SOURCE_SERVER_SELECT>[<SOURCE_DATABASE>].[<SOURCE_SCHEMA>].[<SOURCE_TABLE>] trg with (nolock)
	where not exists(
	    select *
	    from [<TARGET_DATABASE>].[<TARGET_SCHEMA>].[<TARGET_TABLE>] src with (nolock)
	    where <TARGET_TABLE_SEARCH_COLUMN> between @SPERIOD_START_DTTM and @SPERIOD_END_DTTM AND <SOURCE_PK_CONDITION>
	)
	and <SOURCE_TABLE_SEARCH_COLUMN> between @SPERIOD_START_DTTM and @SPERIOD_END_DTTM;

	SET @ERR2 = @@ERROR;
