EXEC MWH.MNG_ETL_CONTROL_MANAGER 'ADD', '<SOURCE_DATA_MART>', '<STORED_PROCEDURE_SCHEMA>.<STORED_PROCEDURE_NAME>', <MIN_CALL_DURATION_MINUTES>,
																	<MAX_CALL_DURATION_MINUTES>, <ETL_PRIORITY>, 1, NULL, NULL, '<SOURCE_TYPE>', 0
GO

SELECT * FROM [MWH].[ETL_CONTROL_MANAGER] WHERE PROCEDURE_NAME = '<STORED_PROCEDURE_SCHEMA>.<STORED_PROCEDURE_NAME>'
GO
